name: Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.22'
          - '1.23'
          - '1.24'
          - '1.x'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          stable: false

      - name: Test
        run: go test -v ./...
